"""Pydantic models for AI-powered resume enrichment."""

from pydantic import BaseModel, Field


class EnrichmentItem(BaseModel):
    """An item identified by AI as needing enrichment."""

    item_id: str  # ID of the experience/project (e.g., "exp_0", "proj_1")
    item_type: str  # "experience" | "project"
    title: str  # Job title or project name
    subtitle: str | None = None  # Company name or project role
    current_description: list[str] = Field(default_factory=list)
    weakness_reason: str  # Why AI flagged this item


class EnrichmentQuestion(BaseModel):
    """A clarifying question generated by AI for an item."""

    question_id: str  # Unique question ID (e.g., "q_0")
    item_id: str  # Which item this question relates to
    question: str  # The question text
    placeholder: str = ""  # Hint for the input field


class AnalysisResponse(BaseModel):
    """Response from AI resume analysis."""

    items_to_enrich: list[EnrichmentItem] = Field(default_factory=list)
    questions: list[EnrichmentQuestion] = Field(default_factory=list)
    analysis_summary: str | None = None  # Optional overall summary


class AnswerInput(BaseModel):
    """User's answer to a clarifying question."""

    question_id: str
    answer: str


class EnhanceRequest(BaseModel):
    """Request to generate enhanced descriptions from answers."""

    resume_id: str
    answers: list[AnswerInput]


class EnhancedDescription(BaseModel):
    """AI-generated enhanced description for an item."""

    item_id: str
    item_type: str  # "experience" | "project"
    title: str  # For display purposes
    original_description: list[str] = Field(default_factory=list)
    enhanced_description: list[str] = Field(default_factory=list)


class EnhancementPreview(BaseModel):
    """Preview of all enhancements before applying."""

    enhancements: list[EnhancedDescription] = Field(default_factory=list)


class ApplyEnhancementsRequest(BaseModel):
    """Request to apply enhancements to the master resume."""

    enhancements: list[EnhancedDescription]


# ============================================
# AI Regenerate Feature Schemas
# ============================================


class RegenerateItemInput(BaseModel):
    """Input for a single item to regenerate."""

    item_id: str  # "exp_0", "proj_1", "skills"
    item_type: str  # "experience" | "project" | "skills"
    title: str
    subtitle: str | None = None
    current_content: list[str] = Field(default_factory=list)


class RegenerateRequest(BaseModel):
    """Request to regenerate selected resume items."""

    resume_id: str
    items: list[RegenerateItemInput]
    instruction: str  # User's feedback/instruction for improvement
    output_language: str = "en"


class RegeneratedItem(BaseModel):
    """Regenerated content for one item."""

    item_id: str
    item_type: str
    original_content: list[str] = Field(default_factory=list)
    new_content: list[str] = Field(default_factory=list)
    diff_summary: str = ""  # AI-generated summary of changes


class RegenerateResponse(BaseModel):
    """Response with all regenerated items."""

    regenerated_items: list[RegeneratedItem] = Field(default_factory=list)
