"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2025-08-21
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - adjust! ###
    op.create_table('llm_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_llm_cache_cache_key'), 'llm_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_llm_cache_created_at'), 'llm_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_cache_model'), 'llm_cache', ['model'], unique=False)
    op.create_index(op.f('ix_llm_cache_prompt_hash'), 'llm_cache', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_llm_cache_strategy'), 'llm_cache', ['strategy'], unique=False)
    op.create_table('llm_cache_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cache_key'], ['llm_cache.cache_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_cache_index_cache_key'), 'llm_cache_index', ['cache_key'], unique=False)
    op.create_index(op.f('ix_llm_cache_index_created_at'), 'llm_cache_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_cache_index_entity_id'), 'llm_cache_index', ['entity_id'], unique=False)
    op.create_index(op.f('ix_llm_cache_index_entity_type'), 'llm_cache_index', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjust! ###
    op.drop_index(op.f('ix_llm_cache_index_entity_type'), table_name='llm_cache_index')
    op.drop_index(op.f('ix_llm_cache_index_entity_id'), table_name='llm_cache_index')
    op.drop_index(op.f('ix_llm_cache_index_created_at'), table_name='llm_cache_index')
    op.drop_index(op.f('ix_llm_cache_index_cache_key'), table_name='llm_cache_index')
    op.drop_table('llm_cache_index')
    op.drop_index(op.f('ix_llm_cache_strategy'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_prompt_hash'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_model'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_created_at'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_cache_key'), table_name='llm_cache')
    op.drop_table('llm_cache')
    # ### end Alembic commands ###
