"""LLM prompt templates."""

from app.prompts.templates import (
    CRITICAL_TRUTHFULNESS_RULES,
    DEFAULT_IMPROVE_PROMPT_ID,
    EXTRACT_KEYWORDS_PROMPT,
    IMPROVE_PROMPT_OPTIONS,
    IMPROVE_RESUME_PROMPT,
    IMPROVE_RESUME_PROMPTS,
    PARSE_RESUME_PROMPT,
    get_language_name,
)

__all__ = [
    "PARSE_RESUME_PROMPT",
    "EXTRACT_KEYWORDS_PROMPT",
    "IMPROVE_RESUME_PROMPT",
    "IMPROVE_RESUME_PROMPTS",
    "IMPROVE_PROMPT_OPTIONS",
    "DEFAULT_IMPROVE_PROMPT_ID",
    "CRITICAL_TRUTHFULNESS_RULES",
    "get_language_name",
]
