# Force Python-only build to avoid Node/npm steps during install
providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"

[phases.install]
cmds = [
  # Ensure pip exists in nix python and upgrade it
  "python3 -m ensurepip --upgrade || true",
  "python3 -m pip install --upgrade pip",
  # Install backend requirements
  "python3 -m pip install -r apps/backend/requirements.txt"
]

# Optional: no build phase needed; backend is Python-only
#[phases.build]
#cmds = ["echo 'No frontend build required'"]

[start]
cmd = "cd apps/backend && uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"
