# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  upgrade-backend:
    desc: Upgrading backend dependencies
    dir: apps/backend
    cmds:
      - uv sync --upgrade
      - uv tool upgrade --all

  upgrade-frontend:
    desc: Upgrading backend dependencies
    dir: apps/frontend
    cmds:
      - bun upgrade

  upgrade:
    desc: Upgrading dependencies
    deps:
      - upgrade-frontend
      - upgrade-backend
    cmds:
      - brew upgrade

  run-backend:
    desc: Running backend
    dir: apps/backend
    cmds:
      - uv run main.py

  run-frontend:
    desc: Running backend
    dir: apps/frontend
    cmds:
      - bun run dev

  run:
    desc: Run the project
    deps:
      - run-frontend
      - run-backend
    cmds:
      - brew upgrade

  docker:
    desc: Running docker with build
    cmds:
      - docker compose up -d --build

  install-backend:
    desc: Installing dependencies backend
    dir: apps/backend
    cmds:
      - uv sync --quiet

  install-frontend:
    desc: Installing dependencies frontend
    dir: apps/frontend
    cmds:
      - bun install --quiet

  install:
    desc: Installing dependencies
    deps:
      - install-frontend
      - install-backend
    cmds:
      - pre-commit install
