"""Deterministic resume-wizard copy in each supported content language."""

_COPY: dict[str, dict[str, str]] = {
    "en": {
        "intro": "Hi — I'll help you build your master resume. What's your name, and what kind of role are you going for?",
        "contact": "What's the best email, phone, or links (LinkedIn / GitHub / site) to include?",
        "summary": "In a sentence or two, how would you describe yourself professionally?",
        "workExperience": "Tell me about one role: title, company, dates, what you did, and any measurable impact.",
        "internships": "Tell me about one internship: title, company, dates, what you worked on, and what changed because of it.",
        "education": "Tell me about your education: school, degree, dates, and any honors or standout coursework.",
        "personalProjects": "Tell me about one project: what you built, why it mattered, the tech you used, and any results.",
        "skills": "What tools, technologies, or skills do you want on your resume?",
        "review": "Let's review what's here before we create your master resume.",
        "next": "What would you like to add next?",
        "warning_name": "Add your name — it's required to create your resume.",
        "warning_contact": "Add at least one contact method (email, phone, or a link).",
        "warning_experience": "Add at least one experience, internship, or project.",
        "warning_education": "Education is empty — skip only if that's intentional.",
        "warning_skills": "Skills are empty — add tools or technologies you've used.",
    },
    "es": {
        "intro": "Hola, te ayudaré a crear tu currículum maestro. ¿Cómo te llamas y qué tipo de puesto buscas?",
        "contact": "¿Qué correo, teléfono o enlaces (LinkedIn, GitHub o sitio web) quieres incluir?",
        "summary": "En una o dos frases, ¿cómo te describirías profesionalmente?",
        "workExperience": "Cuéntame sobre un puesto: cargo, empresa, fechas, qué hiciste y cualquier impacto medible.",
        "internships": "Cuéntame sobre unas prácticas: cargo, empresa, fechas, en qué trabajaste y qué cambió gracias a ello.",
        "education": "Cuéntame sobre tu formación: centro, título, fechas y cualquier reconocimiento o curso destacado.",
        "personalProjects": "Cuéntame sobre un proyecto: qué creaste, por qué era importante, qué tecnología usaste y qué resultados obtuviste.",
        "skills": "¿Qué herramientas, tecnologías o habilidades quieres incluir en tu currículum?",
        "review": "Revisemos el contenido antes de crear tu currículum maestro.",
        "next": "¿Qué te gustaría añadir a continuación?",
        "warning_name": "Añade tu nombre; es necesario para crear el currículum.",
        "warning_contact": "Añade al menos un medio de contacto (correo, teléfono o enlace).",
        "warning_experience": "Añade al menos una experiencia, unas prácticas o un proyecto.",
        "warning_education": "La formación está vacía; omítela solo si es intencional.",
        "warning_skills": "Las habilidades están vacías; añade herramientas o tecnologías que hayas usado.",
    },
    "zh": {
        "intro": "你好，我会帮你创建主简历。你叫什么名字，想应聘哪类职位？",
        "contact": "你想添加哪个电子邮箱、电话号码或链接（LinkedIn、GitHub 或个人网站）？",
        "summary": "请用一两句话描述你的职业背景。",
        "workExperience": "请介绍一段工作经历：职位、公司、时间、工作内容以及可量化的成果。",
        "internships": "请介绍一段实习经历：职位、公司、时间、工作内容以及带来的改变。",
        "education": "请介绍你的教育背景：学校、学位、时间以及荣誉或重点课程。",
        "personalProjects": "请介绍一个项目：你构建了什么、它为何重要、使用了哪些技术以及取得了什么成果。",
        "skills": "你想在简历中列出哪些工具、技术或技能？",
        "review": "创建主简历前，让我们先检查现有内容。",
        "next": "接下来你想添加什么？",
        "warning_name": "请添加姓名；创建简历时必须提供姓名。",
        "warning_contact": "请至少添加一种联系方式（电子邮箱、电话或链接）。",
        "warning_experience": "请至少添加一段工作、实习或项目经历。",
        "warning_education": "教育背景为空；仅在这是有意为之时跳过。",
        "warning_skills": "技能为空；请添加你使用过的工具或技术。",
    },
    "ja": {
        "intro": "こんにちは。マスター履歴書の作成をお手伝いします。お名前と希望する職種を教えてください。",
        "contact": "掲載するメールアドレス、電話番号、リンク（LinkedIn、GitHub、サイト）を教えてください。",
        "summary": "ご自身の職務上の特徴を1〜2文で説明してください。",
        "workExperience": "職歴を1つ教えてください。役職、会社、期間、担当内容、数値で示せる成果を含めてください。",
        "internships": "インターン経験を1つ教えてください。役割、会社、期間、担当内容、その結果を含めてください。",
        "education": "学歴について、学校名、学位、在籍期間、表彰や主な履修内容を教えてください。",
        "personalProjects": "プロジェクトを1つ教えてください。作ったもの、重要だった理由、使用技術、成果を含めてください。",
        "skills": "履歴書に載せたいツール、技術、スキルを教えてください。",
        "review": "マスター履歴書を作成する前に、内容を確認しましょう。",
        "next": "次に何を追加しますか？",
        "warning_name": "氏名を追加してください。履歴書の作成に必要です。",
        "warning_contact": "連絡先（メール、電話、リンク）を少なくとも1つ追加してください。",
        "warning_experience": "職歴、インターン、プロジェクトのいずれかを少なくとも1つ追加してください。",
        "warning_education": "学歴が空です。意図的な場合のみスキップしてください。",
        "warning_skills": "スキルが空です。使用経験のあるツールや技術を追加してください。",
    },
    "pt": {
        "intro": "Olá, vou ajudar você a criar seu currículo mestre. Qual é o seu nome e que tipo de cargo você procura?",
        "contact": "Qual e-mail, telefone ou links (LinkedIn, GitHub ou site) você quer incluir?",
        "summary": "Em uma ou duas frases, como você se descreveria profissionalmente?",
        "workExperience": "Conte sobre um cargo: função, empresa, datas, o que você fez e qualquer impacto mensurável.",
        "internships": "Conte sobre um estágio: função, empresa, datas, em que trabalhou e o que mudou por causa disso.",
        "education": "Conte sobre sua formação: instituição, curso, datas e honras ou disciplinas de destaque.",
        "personalProjects": "Conte sobre um projeto: o que criou, por que foi importante, as tecnologias usadas e os resultados.",
        "skills": "Quais ferramentas, tecnologias ou habilidades você quer incluir no currículo?",
        "review": "Vamos revisar o conteúdo antes de criar seu currículo mestre.",
        "next": "O que você gostaria de adicionar agora?",
        "warning_name": "Adicione seu nome; ele é obrigatório para criar o currículo.",
        "warning_contact": "Adicione pelo menos um contato (e-mail, telefone ou link).",
        "warning_experience": "Adicione pelo menos uma experiência, estágio ou projeto.",
        "warning_education": "A formação está vazia; pule apenas se isso for intencional.",
        "warning_skills": "As habilidades estão vazias; adicione ferramentas ou tecnologias que você usou.",
    },
    "fr": {
        "intro": "Bonjour, je vais vous aider à créer votre CV principal. Quel est votre nom et quel type de poste recherchez-vous ?",
        "contact": "Quelle adresse e-mail, quel téléphone ou quels liens (LinkedIn, GitHub ou site) souhaitez-vous inclure ?",
        "summary": "En une ou deux phrases, comment vous décririez-vous professionnellement ?",
        "workExperience": "Parlez-moi d’un poste : intitulé, entreprise, dates, missions et résultats mesurables.",
        "internships": "Parlez-moi d’un stage : intitulé, entreprise, dates, travaux réalisés et résultats obtenus.",
        "education": "Parlez-moi de votre formation : établissement, diplôme, dates, distinctions ou cours marquants.",
        "personalProjects": "Parlez-moi d’un projet : ce que vous avez créé, son importance, les technologies utilisées et les résultats.",
        "skills": "Quels outils, technologies ou compétences souhaitez-vous faire figurer sur votre CV ?",
        "review": "Vérifions le contenu avant de créer votre CV principal.",
        "next": "Que souhaitez-vous ajouter ensuite ?",
        "warning_name": "Ajoutez votre nom ; il est nécessaire pour créer le CV.",
        "warning_contact": "Ajoutez au moins un moyen de contact (e-mail, téléphone ou lien).",
        "warning_experience": "Ajoutez au moins une expérience, un stage ou un projet.",
        "warning_education": "La formation est vide ; ne la passez que si c’est intentionnel.",
        "warning_skills": "Les compétences sont vides ; ajoutez les outils ou technologies que vous avez utilisés.",
    },
    "ko": {
        "intro": "안녕하세요. 마스터 이력서 작성을 도와드리겠습니다. 이름과 희망하는 직무를 알려 주세요.",
        "contact": "기재할 이메일, 전화번호 또는 링크(LinkedIn, GitHub, 웹사이트)를 알려 주세요.",
        "summary": "본인의 전문 경력을 한두 문장으로 설명해 주세요.",
        "workExperience": "경력 한 가지를 알려 주세요. 직책, 회사, 기간, 담당 업무와 측정 가능한 성과를 포함해 주세요.",
        "internships": "인턴 경험 한 가지를 알려 주세요. 역할, 회사, 기간, 담당 업무와 그 결과를 포함해 주세요.",
        "education": "학력에 대해 알려 주세요. 학교, 학위, 기간, 수상 또는 주요 과목을 포함해 주세요.",
        "personalProjects": "프로젝트 한 가지를 알려 주세요. 만든 것, 중요했던 이유, 사용 기술과 결과를 포함해 주세요.",
        "skills": "이력서에 넣고 싶은 도구, 기술 또는 역량을 알려 주세요.",
        "review": "마스터 이력서를 만들기 전에 내용을 검토해 보겠습니다.",
        "next": "다음으로 무엇을 추가하시겠습니까?",
        "warning_name": "이름을 추가해 주세요. 이력서 생성에 필요합니다.",
        "warning_contact": "연락처(이메일, 전화 또는 링크)를 하나 이상 추가해 주세요.",
        "warning_experience": "경력, 인턴 또는 프로젝트를 하나 이상 추가해 주세요.",
        "warning_education": "학력이 비어 있습니다. 의도한 경우에만 건너뛰세요.",
        "warning_skills": "기술이 비어 있습니다. 사용해 본 도구나 기술을 추가해 주세요.",
    },
}


def wizard_copy(language: str, key: str) -> str:
    """Return deterministic wizard copy, falling back to English."""
    localized = _COPY.get(language, _COPY["en"])
    return localized.get(key, _COPY["en"][key])
