name: Frontend CI

on:
  push:
    branches: [ main, "security-hardening-neon" ]
  pull_request:
    branches: [ main, "security-hardening-neon" ]

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    env:
      CI: 'true'
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Lint (non-blocking)
        run: |
          npm run lint || echo "Lint warnings/errors ignored in CI"

      - name: Run tests
        run: npm test -- --runInBand

      - name: Build
        run: npm run build
